### ISSUE TITLE
--json does NOT return json

### ISSUE THREAD

**Issue by nickofthyme** [moos/istanbul-diff#1]
https://github.com/moos/istanbul-diff/blob/0a26bce15b6aaad98faf75aa8ac481184a7f261c/bin/cli.js#L56

This returns the javascript object `diff` not the json version.

Should be

```js
console.log(JSON.strigify(delta));
```

**Comment by moos** [comment]
Fixed in v2.0.0.

**Comment by nickofthyme** [comment]
Thanks @moos
